### ISSUE TITLE
Loading jobs after initialization of sails

### ISSUE THREAD

**Issue by ezhlobo** [ghaiklor/sails-hook-cron#103]
The problem I have: jobs don't have access to services and all global variables so they are not really convenient.

The idea how we can solve that: we can specify all jobs separately in `api/jobs` and load them in callback for `sails.on('ready')`. 

Does it work for you? If yes I can implement it quickly and send a PR.

**Comment by ghaiklor** [comment]
@ezhlobo it does - https://github.com/ghaiklor/sails-hook-cron/blob/dev/src/index.js#L13-L13

**Comment by ezhlobo** [comment]
@ghaiklor yeah, I see. It means that we can use services only in onTick and onComplete. Let me to explain my task.

I need to cache results in redis. I have a service for this (because I use cached results in my app). For caching I'm going to start task in a background every 30 minutes which will get results from some API. And I don't want to create a connection between server and redis in onTick.

**Comment by cope** [comment]
So, are we able to use services in cron hook? Because I just tried and it fails :(

**Comment by ezhlobo** [comment]
@cope you can use services in `onTick` and `onComplete` only for now, as I know...

**Comment by cope** [comment]
Yeah, it works, I did the dumb... I created the service file without the .js extension, so of course it was not finding it... :(

Some days.........

**Comment by ezhlobo** [comment]
Okay

**Comment by nicolapalavecino** [comment]
I see you managed to resolve this, could you post a code snippet on how I can define the files in 'api/jobs' folder? I'm trying to call sails specific variables like `sails.log.error()` or some sails `services` defined by myself within the `onTick()` function, and an error shows up (`ReferenceError: sails is not defined`)

**Comment by cope** [comment]
@nicolapalavecino I'm not familiar with api/jobs? [Anatomy of a Sails app](https://sailsjs.com/documentation/anatomy/api)

My problem was caused by me, I did not properly name the service file, I omitted the .js extension.
