### ISSUE TITLE
Cron syntax (schedule field)

### ISSUE THREAD

**Issue by muriloqr** [ghaiklor/sails-hook-cron#137]
Hello,

I have passed a problem with the schedule field, in universal cron, the syntax is minute/hour/dayOfMonth/month/dayOfWeek according the image below

https://i1.wp.com/www.debian-tutorials.com/tutoriale/crontab-syntax.gif?resize=400%2C162

But the syntax in schedule field is ['seconds', 'minutes', 'hours', 'dayOfMonth', 'month', 'dayOfWeek'], and this, is not specified in the Readme.

If possible, fix this for the next people, i hope it helps

Thanks

**Comment by muriloqr** [comment]
I have just done two pull requests:

https://github.com/ghaiklor/sails-hook-cron/pull/139

https://github.com/ghaiklor/sails-hook-cron/pull/138

**Comment by ghaiklor** [comment]
@muriloqr done, thanks for help 👍
