### ISSUE TITLE
start: true doesn't start job

### ISSUE THREAD

**Issue by greghesp** [ghaiklor/sails-hook-cron#156]
Perhaps I'm not understanding the documents correctly, however here is my job.

My expectation here is that this job will run every Sunday at 1am, however it will also run straight away when sails lifts.  This doesn't appear to happen

```
  firstJob: {
    schedule: '0 0 1 * * 0',
    onTick: function() {
      console.log('I will trigger at 01:00 every Sunday');
    },
    timezone: 'America/Sao_Paulo',
    start: true,
  },
```

**Comment by dev2games** [comment]
That's weird, I wasn't able to recreate the issue are you on the latest version of Sails? Also does your timezone accurately represent your area? For me I had to change it to America/New_York

**Comment by Kerwood** [comment]
Same issue here.. `Sails 0.12.14`. Not using `timezone`.

**Comment by Kerwood** [comment]
The `start: true` property does not automatically run the task at Sails start. It just "starts" the task. Like you kan create a task and set `start: false` and it will not run.
I've added the `runOnInit` property. Have a look at the pull request. https://github.com/ghaiklor/sails-hook-cron/pull/170
