### ISSUE TITLE
Cron (month) issue

### ISSUE THREAD

**Issue by dev2games** [ghaiklor/sails-hook-cron#163]
According to the official Cron page, the code below should be 9/18/2017 at 10:00 PM. Only problem is, in this hook month starts at 0, instead of 1.

```
module.exports.cron = {
    job: {
        schedule: '0 0 22 18 9 *',
        onTick: function() {
            console.log('Output');
        },
        timezone: 'America/New_York',
        start: true
    }
};

```
Basically the only way it would work for 9/18/2017 is if the following schedule variable is

```
schedule: '0 0 22 18 8 *',
```

https://en.wikipedia.org/wiki/Cron#Overview

**Comment by ghaiklor** [comment]
@dev2games I'm using `node-cron` package which accepts these strings. Take a look there, may be something wrong with it. I do nothing with cron format, just passing it to this package.
