### ISSUE TITLE
Non working example

### ISSUE THREAD

**Issue by dev2games** [ghaiklor/sails-hook-cron#164]
onComplete is never called.

```
module.exports.cron = {
  myJob: {
    schedule: '* * * * * *',
    onTick: function() {
      console.log('I am triggering when time is come');
    },
    onComplete: function() {
      console.log('I am triggering when job is complete');
    },
    start: true, // Start task immediately
    timezone: 'Ukraine/Kiev', // Custom timezone
    context: undefined // Custom context for onTick callback
  }
};
```

**Comment by nicolapalavecino** [comment]
It's happening the same thing in my project... (`onComplete` is never called)

**Comment by maximilianmeier** [comment]
onComplete is only executed if the job is stopped or is called manually by `onTick()`

> onComplete - [OPTIONAL] - A function that will fire when the job is stopped with job.stop(), and may also be called by onTick at the end of each run.

See for more details: https://github.com/kelektiv/node-cron

**Comment by ghaiklor** [comment]
@maximilianmeier thanks for reference. I'm assuming that it is expected behavior, so closing this one.
