### ISSUE TITLE
Since today "npm i sails-hook-cron" installs an empty folder

### ISSUE THREAD

**Issue by simonmilz** [ghaiklor/sails-hook-cron#172]
![image](https://user-images.githubusercontent.com/5016123/31440540-9b63c3f6-ae90-11e7-91cc-2f712f6b442a.png)

Any clue why this happens? I just run "npm i sails-hook-cron" in an empty folder with:

    "node": "8.6.0",
    "npm": "5.5.1"

**Comment by magiksd** [comment]
This just crashed my production server after a "npm i" ...

**Comment by simonmilz** [comment]
Mine too... Luckily Staging ;)

**Comment by ghaiklor** [comment]
@simonmilz wow, guys, sorry. Seems like `.npmignore` and `.gitignore` are conflicting. I'll fix this right now. For not, install `npm install sails-hook-cron@2.2.0`.

**Comment by simonmilz** [comment]
👍🏼

**Comment by ghaiklor** [comment]
@simonmilz published as new version - 2.2.2. Can you check if everything is ok and send response here, thanks.

**Comment by simonmilz** [comment]
Yep, will do it on saturday.

**Comment by glenwinters** [comment]
2.2.0 has been working for me.

Today, when I updated to 2.2.2, my app doesn't load and shows `SyntaxError: Unexpected token {`.

Can you post the tag of 2.2.2 on GitHub? I'd like to see the diff to troubleshoot.

**Comment by glenwinters** [comment]
I realized I could install the different versions via npm and compare the files. It looks like 2.2.2 is using ES6, and 2.2.0 was not. Shouldn't this be considered a breaking change and not be a patch release?

**Comment by simonmilz** [comment]
@ghaiklor works for me now with 2.2.2! Thanks!

**Comment by ghaiklor** [comment]
@simonmilz great, thanks for the response. We can close this issue for now, since it was fixed in 2.2.2.
