### ISSUE TITLE
Cron running for every second

### ISSUE THREAD

**Issue by sabarish3012** [ghaiklor/sails-hook-cron#180]
Hi , I have scheduled the cron to run on 11 47 am , the cron job is being triggered multiple times.

https://goo.gl/YXBnMr

There is a open issue in Stackoverflow too. Would you please revert.

![image](https://user-images.githubusercontent.com/20104770/33818466-1743cc96-de6b-11e7-82b8-801a1aeb1e12.png)

**Comment by stokesbga** [comment]
What ended up happening with this?

**Comment by nicolapalavecino** [comment]
In that case the `schedule` variable should be `'00 47 11 * * *'` or `'47 11 * * *'`. Is this your case? Maybe you are typing `'* 47 11 * * *'` instead

**Comment by ghaiklor** [comment]
I'm using node-cron package here, so for any issues with cron, please refer to https://github.com/kelektiv/node-cron#available-cron-patterns
