### ISSUE TITLE
Cron scheduled dosen't run at all 

### ISSUE THREAD

**Issue by sabarish3012** [ghaiklor/sails-hook-cron#182]
sendKitchenUpdates: {
        schedule: '02 0 * * *',
        onTick: function() {
            var moment = require("moment");
            startLog(moment);
            console.log('Cron Strarted');
            //Day less than updated
            dayCheck = 1;
            getfirebasedata(dayCheck, moment);
        },
        // onComplete: function() {
        //     var moment = require("moment");
        //     console.log('completed');
        //     endLog(moment);
        // },
        start: false, // Start task immediately
        timezone: 'Asia/Kolkata', // Custom timezone
    }

**Comment by ghaiklor** [comment]
I'm using node-cron package here, so for any issues with cron, please refer to https://github.com/kelektiv/node-cron#available-cron-patterns
