### ISSUE TITLE
Cron run twice or more based on the time the cron is saved

### ISSUE THREAD

**Issue by freitasmurillo** [ghaiklor/sails-hook-cron#190]
This project has `https://www.npmjs.com/package/cron` as dependency.
This dependency used to have a bug that was fixed when a new version was released.
But your last release still point to a version that contains this bug.

I saw in your `dev` branch that you have updated the dependency but no release was made since the update.

Do you have any idea when you pretend release?

**Comment by ghaiklor** [comment]
@freitasmurillo I've updated `sails-hook-cron` to `latest: 3.0.0` version.

**Comment by freitasmurillo** [comment]
@ghaiklor Thank you for the release.
