### ISSUE TITLE
how to pass parram to onTick function 

### ISSUE THREAD

**Issue by ffaouzif** [ghaiklor/sails-hook-cron#197]
i try to pass some params to ontick function in cron config like this : 

//AgentController.js 

module.exports = {

         var resultGetLiveAgentSerivce;
         var opts = {
            name : 'jefery'
         };
         var results = sails.hooks.cron.jobs.getLiveAgentJob.start(opts, function(err, results){
	        resultGetLiveAgentSerivce: results;
	        console.log(resultGetLiveAgentSerivce);
	  });
};

 //cron.js

module.exports.cron = {
  
      getLiveAgentJob:  {

          schedule: '*/5 * * * * *',

          onTick: function(option, callback) {

      console.log(option.name);
      var err = '';
      var results = '';

      //call service AgentService , function GetLiveAgents that return a query mysql 
      AgentService.GetLiveAgents(option.name, function(err, results){

        if(err){

          err =  err;
          return err;
        }

        if(results){

          results =  results;
          console.log(results);
         
        }
        });
 
    },

    start: false
  }
};

option.name is undifened !!

**Comment by ghaiklor** [comment]
@ffaouzif read [cron api](https://www.npmjs.com/package/cron#api) and read more about jobs API, there is no such way
