### ISSUE TITLE
cron jobs not running on digitalocean server.

### ISSUE THREAD

**Issue by satishverma143** [ghaiklor/sails-hook-cron#213]
Please help me.
I have created few cron jobs in sails 1.0 version.
and it was running on heroku app for 2 days only.
when I have deployed my application on digitalocean then it's not working any more.
please tell me what should i do?

**Comment by ghaiklor** [comment]
There is no difference between running them on heroku or digital ocean. If they were running on Heroku, then they are running on DO. Most of all, the reason behind this is something with your setup on DO.
