### ISSUE TITLE
How to schedule a cron for every one hour?

### ISSUE THREAD

**Issue by avanisindhav** [ghaiklor/sails-hook-cron#247]
I am Trying to Schedule it every one hour but it running at every seconds.

**Comment by avanisindhav** [comment]
I am Trying to Schedule it  every one hour but it running at every seconds.

**Comment by avanisindhav** [comment]
I am Trying to Schedule it every one hour but it running at every seconds.

**Comment by ghaiklor** [comment]
I'm using node-cron package here, so for any issues with cron, please refer to https://github.com/kelektiv/node-cron#available-cron-patterns

**Comment by amrendraw3** [comment]
In order to run every hour:

`*/60 * * * *`
