### ISSUE TITLE
sails.config.environment

### ISSUE THREAD

**Issue by certifirm** [ghaiklor/sails-hook-cron#251]
Is it posible to use sails.config.environment?  Or I must to start the cron job from a controller, for example?  

Thanks

**Comment by ghaiklor** [comment]
@jotae1e https://github.com/ghaiklor/sails-hook-cron/issues/225 here says that you can try to move your configuration for cron to local configuration. That way, it should work (based on issue).

**Comment by ghaiklor** [comment]
Sails is now accessible from `this` in tick functions - da70935a5a3d38fa38b252f5c0a90be27745373f

**Comment by certifirm** [comment]
I didn't try this release.

I was accessing sails.config.enviroment with require:
const sails = require('sails');

It was working until now.

Thanks anyway.
