### ISSUE TITLE
local.js = bad instructions

### ISSUE THREAD

**Issue by dmitrye** [ghaiklor/sails-hook-cron#258]
It's bad instructions to tell people that they should use local.js for the global object. local.js is by default in .gitignore and not mean to be committed to SCM nor available in any other environment other than the local (hence the name) development environment.

The reason sails is not working is that you're calling an underlying library (cron) and passing in onTick from the config file. However, there is no context being set per cron instructions:

> context - [OPTIONAL] - The context within which to execute the onTick method. This defaults to the cronjob itself allowing you to call this.stop(). However, if you change this you'll have access to the functions and values within your context object.

I believe that the sails object needs to be passed into context. I'm therefore proposing to modify the index.js so that it looks like this:

```
jobs.forEach(job => {
          this.jobs[job] = new CronJob(
            config[job].schedule,
            config[job].onTick,
            config[job].onComplete,
            typeof config[job].start === 'boolean' ? config[job].start : true,
            config[job].timezone,
            config[job].context || sails,
            typeof config[job].runOnInit === 'boolean' ? config[job].runOnInit : false
          );
        });
```

Then inside the config definition you use "this" to represent sails:
```
module.exports.cron = {
  testJob: {
    schedule: '* * * * * *',
    onTick: async function () {
      try {
        console.log(this.models); // returns all models available in sails object
      }catch(e){
        console.log(e);
      }
    }
  }
};
```

**Comment by ghaiklor** [comment]
@dmitrye can you make a PR with this change and update the test to check whether it works?

**Comment by dmitrye** [comment]
@ghaiklor The tests you currently have in place validate the JSON of the configuration is present but they do not validate that the Cron is actually working. The new test I added will in essence handle both that the cron functionality is working and that the sails object is accessible (by modifying it).

**Comment by ghaiklor** [comment]
@dmitrye yeah, I saw, thanks for the PR. Just one minor issue, wrote there.

**Comment by ghaiklor** [comment]
You didn't respond, so I found some free time to adjust PR - da70935a5a3d38fa38b252f5c0a90be27745373f

Already fixed and published on npm.

**Comment by dmitrye** [comment]
@ghaiklor Thanks for handling it. I was pretty busy last week and didn't have a chance to do anything on the side.
