### ISSUE TITLE
contexr

### ISSUE THREAD

**Issue by makah** [ghaiklor/sails-hook-cron#262]
It may be interesting write a section on README about context. Something like:

> There are three states for the context (this)
> 
> 1. If you don't declare context: this = sails
> 2. If you declare `context = underfined`: this = original cron's library context
> 	You still access `sails` from global variable
> 3. If you declare `context = <any_object>`: this = any_object (as we expect)

**Comment by ghaiklor** [comment]
@makah sure, feel free to make clarifications in PR, I'm open to it

**Comment by ghaiklor** [comment]
Done and published in the latest version
