### ISSUE TITLE
How can I enable/disable the cron service?

### ISSUE THREAD

**Issue by ricardovigatti** [ghaiklor/sails-hook-cron#267]
I want to use some kind of configuration to enable or disable the cron service. Is this possible?

Something like `enableCron: false` at config/custom.js.

**Comment by ghaiklor** [comment]
I believe there is a configuration in Sails where you can disable specific hooks. Please, refer to Sails documentation for that.

**Comment by ricardovigatti** [comment]
Nice. I was able to do it.

```javascript
sails.lift({
  hooks: {
     cron: false
  },

  [ ... ]
});
```
