### ISSUE TITLE
Implement locking of tasks when they are overexecuted in time

### ISSUE THREAD

**Issue by ghaiklor** [ghaiklor/sails-hook-cron#4]
For example, you have cron task with this schedule `* * * * * *`. If you run in this job hard operation like queries to database, we can make overflow in memory because of a lot parallel tasks.

**Comment by ghaiklor** [comment]
Closing this task, because we can't trace async operations. So if you are using async task - it's all on you to handle execution flow.

**Comment by patrickstorm** [comment]
For those of you looking for an answer to this. I was able to get this working by `.stop()`ing the cron task immediately in the `onTick` function and then `.start()`ing it back up when I know the process is finished. Not perfect, but worked for my implementation.
