### ISSUE TITLE
schedule: '* * * * * *',

### ISSUE THREAD

**Issue by Clan-Utility** [ghaiklor/sails-hook-cron#8]
In README.md, you have

```
schedule: '* * * * * *',  // 6 fields!
```

and  

```
schedule: '*/5 * * * *',   // 5 fields!
```

It should always be 5 fields, right?

**Comment by ghaiklor** [comment]
@Clan-Utility strange, just checked. CronTab has 5 fields, but node-cron library has 6 fields. And who is right? :smiley_cat:
